FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

RUN dotnet dev-certs https

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .


ENV ASPNETCORE_URLS https://localhost:5000
ENV Jwt.SecretKey secretKey3keykey
ENV Jwt.Issuer https://localhost:5000
ENV Jwt.Audience https://localhost:5000
ENV Db.Password dbPassword

ENTRYPOINT ["dotnet", "Solvro_city.dll"]
